remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PEER2PEER Transboundary Water Security
description: Google Earth Engine Training 2025
logo: ./assets/logo1.png
favicon: true

navigation:
  - name: Google Colab setup
    link: ./assets/GEE%20in%20Python%20setup%20instructions/GEEinPythonsetupinstructions.html
  - name: Notebooks
    link: https://github.com/UCI-CHRS/GEE-Training-2025/blob/main/notebooks
  - name: Example: Explore GEE Data Catalog
    link: ./examples/Tutorial01_Access_Data.html
