remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title:  
description: Materials for the Google Earth Engine Training held by the Accelnet PEER2PEER early career researchers in Dar es Salaam, Tanzania, June 2025.

logo: ./assets/logo.png

navigation:
  - name: Home Page
    link: ./
  - name: Get Started
    link: ./assets/GEE%20in%20Python%20setup%20instructions/GEEinPythonsetupinstructions.html
  - name: Notebooks
    link: https://github.com/UCI-CHRS/GEE-Training-2025/blob/main/notebooks
  - name: Examples
    sublist:
      - name: Explore GEE Data Catalog
        link: ./examples/Tutorial01_Access_Data.html
