remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PEER2PEER Transboundary Water Security
description: Google Earth Engine Training 2025
logo: ./assets/logo1.png
favicon: true

navigation:
  - name: Slides
    link: https://docs.google.com/presentation/d/e/2PACX-1vRv47Sy9SaPYx3K8yWOP7GpLiMNTKY4fRSLrVjOkbu1uGb5vRgVNJCzZM0uO1gVDQke-3BCaCS02s5E/pub?start=false&loop=false&delayms=3000
  - name: Notebooks
    link: https://github.com/UCI-CHRS/GEE-Training-2025/blob/main/notebooks
  - name: Additional Resources
    link: ./assets/Additional%20Resources.md
